openapi: 3.0.0
info:
  title: WABToDo-back-end
  version: 1.0.0

paths:
  /api/users/registration/:
    post:
      summary: Registering a user as a client or as a team member
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                phoneNumber:
                  type: string
                password:
                  type: string
                isTeamMember:
                  type: boolean
                  default: false

      responses:
        '201':
          description: Redirect the user to the login page
          content:
            application/json:
              example:
                message: "Account successfully created"
        '400':
          description: Stay on the same page
          content:
            application/json:
              example:
                message: "Entered data is not valid"

  /api/users/login/:
    post:
      summary: Create user access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string

      responses:
        '201':
          description: Return access token and redirect to dashboard
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              example:
                token: user_json_web_token

        '401':
          description: Stay on the same page
          content:
            application/json:
              example:
                detail: Invalid email or password.
